# Generated by Django 5.2.15 on 2026-07-17 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_end_date_project_start_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='created_by',
            new_name='owner',
        ),
    ]
