# Generated by Django 4.2.30 on 2026-09-30 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('EDITOR', 'Editor'), ('VIEWER', 'Viewer')], default='VIEWER', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_project_invitations', to=settings.AUTH_USER_MODEL)),
                ('invited_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_invitations', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('EDITOR', 'Editor'), ('VIEWER', 'Viewer')], default='VIEWER', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project'], name='proj_member_project_idx'), models.Index(fields=['user'], name='proj_member_user_idx'), models.Index(fields=['project', 'user'], name='proj_member_proj_user_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='projectmember',
            constraint=models.UniqueConstraint(fields=('project', 'user'), name='unique_project_membership'),
        ),
        migrations.AddIndex(
            model_name='projectinvitation',
            index=models.Index(fields=['project'], name='proj_inv_project_idx'),
        ),
        migrations.AddIndex(
            model_name='projectinvitation',
            index=models.Index(fields=['invited_user'], name='proj_inv_invited_user_idx'),
        ),
        migrations.AddIndex(
            model_name='projectinvitation',
            index=models.Index(fields=['invited_by'], name='proj_inv_invited_by_idx'),
        ),
        migrations.AddIndex(
            model_name='projectinvitation',
            index=models.Index(fields=['status'], name='proj_inv_status_idx'),
        ),
        migrations.AddIndex(
            model_name='projectinvitation',
            index=models.Index(fields=['project', 'invited_user'], name='proj_inv_proj_user_idx'),
        ),
        migrations.AddIndex(
            model_name='projectinvitation',
            index=models.Index(fields=['invited_user', 'status'], name='proj_inv_user_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='projectinvitation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('project', 'invited_user'), name='uniq_pending_proj_invitation'),
        ),
    ]
