import React from 'react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import './MarkdownRenderer.css';

/**
 * MarkdownRenderer component for NForge.
 * Reliably parses and renders Markdown generated by AI (headings, lists, bold/italics,
 * tables, blockquotes, code, links) using react-markdown and remark-gfm.
 */
function MarkdownRenderer({ content, className = '' }) {
    if (!content && content !== 0) {
        return null;
    }

    const textContent = typeof content === 'string' ? content : String(content);

    return (
        <div className={`research-markdown ${className}`.trim()}>
            <ReactMarkdown
                remarkPlugins={[remarkGfm]}
                components={{
                    // Wrap tables in an overflow container for responsive horizontal scrolling
                    table: ({ node, ...props }) => (
                        <div className="markdown-table-wrapper">
                            <table {...props} />
                        </div>
                    ),
                    // Ensure links open safely in a new tab
                    a: ({ node, href, children, ...props }) => (
                        <a
                            href={href}
                            target="_blank"
                            rel="noopener noreferrer"
                            {...props}
                        >
                            {children}
                        </a>
                    ),
                }}
            >
                {textContent}
            </ReactMarkdown>
        </div>
    );
}

export default MarkdownRenderer;
