"""
backend/ai/citations.py

Phase 7.5.1 — Citation-Aware Backend Foundation for NForge.

Provides a controlled, immutable citation representation and resolution helpers
connecting AI-generated claims to validated retrieved evidence (ResearchEvidence,
PaperChunk, Paper).

Key principles:
1. ResearchEvidence is the source of truth for persisted evidence.
2. Citation IDs are deterministically generated by NForge, never invented by AI/LLMs.
3. Invalid sources and cross-project evidence are strictly rejected.
4. Duplicate evidence is coalesced into unified citation references.
5. Missing page numbers are handled gracefully (null / unavailable).
"""

from dataclasses import dataclass
from typing import Optional, List, Dict, Any, Union, Set
from django.db.models import QuerySet

from papers.models import Paper
from ai.models import PaperChunk, ResearchEvidence, ResearchMessage, ResearchSession


class InvalidCitationError(ValueError):
    """Raised when citation or source reference validation fails."""
    pass


class CrossProjectCitationError(InvalidCitationError):
    """Raised when evidence or sources cross project boundaries."""
    pass


class CitationResolutionError(ValueError):
    """Raised when a citation cannot be resolved to valid evidence."""
    pass


def build_citation_id(paper_id: Any, chunk_id: Optional[Any] = None) -> str:
    """
    Generate a deterministic citation ID string from validated IDs.
    Examples:
        build_citation_id(1, 4) -> 'cite_p1_c4'
        build_citation_id(1, None) -> 'cite_p1'
    """
    if paper_id is None:
        raise InvalidCitationError("paper_id is required to build a citation ID.")
    try:
        pid = int(paper_id)
        if pid <= 0:
            raise ValueError()
    except (ValueError, TypeError):
        raise InvalidCitationError(f"Invalid paper_id: {paper_id}. Must be a positive integer.")

    if chunk_id is not None:
        try:
            cid = int(chunk_id)
            if cid <= 0:
                raise ValueError()
            return f"cite_p{pid}_c{cid}"
        except (ValueError, TypeError):
            raise InvalidCitationError(f"Invalid chunk_id: {chunk_id}. Must be a positive integer.")

    return f"cite_p{pid}"


def parse_citation_id(citation_id: str) -> Dict[str, Optional[int]]:
    """
    Parse a citation ID string into component IDs.
    'cite_p1_c4' -> {'paper_id': 1, 'chunk_id': 4}
    'cite_p1' -> {'paper_id': 1, 'chunk_id': None}
    """
    if not isinstance(citation_id, str) or not citation_id.startswith("cite_p"):
        raise InvalidCitationError(f"Invalid citation ID format: {citation_id}")

    parts = citation_id.split("_")
    if len(parts) < 2 or not parts[1].startswith("p"):
        raise InvalidCitationError(f"Invalid citation ID format: {citation_id}")

    try:
        paper_id = int(parts[1][1:])
        if paper_id <= 0:
            raise ValueError()
    except (ValueError, IndexError):
        raise InvalidCitationError(f"Cannot parse valid paper_id from {citation_id}")

    chunk_id = None
    if len(parts) >= 3:
        if not parts[2].startswith("c"):
            raise InvalidCitationError(f"Invalid citation ID chunk component: {parts[2]}")
        try:
            chunk_id = int(parts[2][1:])
            if chunk_id <= 0:
                raise ValueError()
        except (ValueError, IndexError):
            raise InvalidCitationError(f"Cannot parse valid chunk_id from {citation_id}")

    return {
        "paper_id": paper_id,
        "chunk_id": chunk_id,
    }


@dataclass(frozen=True)
class CitationReference:
    """
    Controlled citation reference connecting an AI-generated claim to retrieved evidence.
    """
    citation_id: str
    citation_key: str
    paper_id: int
    paper_title: str
    chunk_id: Optional[int]
    page_number: Optional[int]
    text: str = ""
    evidence_id: Optional[int] = None

    def to_dict(self) -> Dict[str, Any]:
        return {
            "citation_id": self.citation_id,
            "citation_key": self.citation_key,
            "paper_id": self.paper_id,
            "paper_title": self.paper_title,
            "chunk_id": self.chunk_id,
            "page_number": self.page_number,
            "text": self.text,
            "evidence_id": self.evidence_id,
        }


@dataclass(frozen=True)
class NumberedCitation:
    """
    Deterministic, user-facing numbered citation representation.
    Retains the internal citation_id while mapping to sequential index [1], [2], etc.
    """
    number: int
    label: str
    citation_id: str
    paper_id: int
    paper_title: str
    chunk_id: Optional[int]
    page_number: Optional[int]
    evidence_id: Optional[int] = None
    text: str = ""

    def to_map_entry(self) -> Dict[str, Any]:
        """Convert to the frontend citation map dictionary format."""
        return {
            "citation_id": self.citation_id,
            "paper_id": self.paper_id,
            "paper_title": self.paper_title,
            "chunk_id": self.chunk_id,
            "page_number": self.page_number,
            "evidence_id": self.evidence_id,
        }

    def to_dict(self) -> Dict[str, Any]:
        """Convert to full structured dictionary including number, label, and text."""
        return {
            "number": self.number,
            "label": self.label,
            "citation_id": self.citation_id,
            "paper_id": self.paper_id,
            "paper_title": self.paper_title,
            "chunk_id": self.chunk_id,
            "page_number": self.page_number,
            "evidence_id": self.evidence_id,
            "text": self.text,
        }


def create_citation_reference(
    paper: Paper,
    chunk: Optional[PaperChunk] = None,
    page_number: Optional[int] = None,
    text: str = "",
    evidence: Optional[ResearchEvidence] = None,
    expected_project: Optional[Any] = None,
) -> CitationReference:
    """
    Create a validated CitationReference from models.
    Validates paper instance, chunk-paper relationship, and project isolation.
    """
    if not isinstance(paper, Paper):
        raise InvalidCitationError("paper must be an instance of Paper.")

    expected_project_id = None
    if expected_project is not None:
        expected_project_id = expected_project.id if hasattr(expected_project, "id") else int(expected_project)
        if paper.project_id != expected_project_id:
            raise CrossProjectCitationError(
                f"Cross-project evidence rejected: paper '{paper.title}' (project {paper.project_id}) "
                f"does not belong to expected project {expected_project_id}."
            )

    chunk_id = None
    resolved_page = page_number
    resolved_text = text or ""

    if chunk is not None:
        if not isinstance(chunk, PaperChunk):
            raise InvalidCitationError("chunk must be an instance of PaperChunk.")
        if chunk.paper_id != paper.id:
            raise InvalidCitationError(
                f"Chunk ID {chunk.id} does not belong to paper '{paper.title}' (ID {paper.id})."
            )
        chunk_id = chunk.id
        if resolved_page is None:
            resolved_page = chunk.page_number
        if not resolved_text:
            resolved_text = chunk.text

    evidence_id = None
    if evidence is not None:
        if not isinstance(evidence, ResearchEvidence):
            raise InvalidCitationError("evidence must be an instance of ResearchEvidence.")
        if evidence.paper_id != paper.id:
            raise InvalidCitationError(
                f"Evidence ID {evidence.id} paper mismatch: expected {paper.id}, got {evidence.paper_id}."
            )
        evidence_id = evidence.id
        if resolved_page is None:
            resolved_page = evidence.page_number
        if not resolved_text:
            resolved_text = evidence.text
        if chunk_id is None and evidence.chunk_id:
            chunk_id = evidence.chunk_id

    cid = build_citation_id(paper.id, chunk_id)
    return CitationReference(
        citation_id=cid,
        citation_key=cid,
        paper_id=paper.id,
        paper_title=paper.title,
        chunk_id=chunk_id,
        page_number=resolved_page,
        text=resolved_text,
        evidence_id=evidence_id,
    )


def generate_citations_from_evidence(
    evidence_items: Union[List[ResearchEvidence], QuerySet],
    expected_project: Optional[Any] = None,
) -> List[CitationReference]:
    """
    Generate a deduplicated list of CitationReference objects from ResearchEvidence instances.
    Enforces project scoping and deduplication.
    """
    if evidence_items is None:
        return []

    citations = []
    seen_keys: Set[Any] = set()

    expected_project_id = None
    if expected_project is not None:
        expected_project_id = expected_project.id if hasattr(expected_project, "id") else int(expected_project)

    for ev in evidence_items:
        if not isinstance(ev, ResearchEvidence):
            raise InvalidCitationError(f"Expected ResearchEvidence instance, got {type(ev)}.")

        paper = ev.paper
        if expected_project_id is not None and paper.project_id != expected_project_id:
            raise CrossProjectCitationError(
                f"Cross-project evidence rejected: evidence {ev.id} belongs to project {paper.project_id}, "
                f"expected project {expected_project_id}."
            )

        dedup_key = (ev.paper_id, ev.chunk_id) if ev.chunk_id is not None else (ev.paper_id, ev.page_number, ev.text[:100])
        if dedup_key in seen_keys:
            continue
        seen_keys.add(dedup_key)

        ref = create_citation_reference(
            paper=paper,
            chunk=ev.chunk,
            page_number=ev.page_number,
            text=ev.text,
            evidence=ev,
            expected_project=expected_project_id,
        )
        citations.append(ref)

    return citations


def validate_source_dict(
    source: Any,
    valid_chunk_map: Optional[Dict[int, PaperChunk]] = None,
    allowed_papers: Optional[Union[List[Paper], Dict[int, Paper]]] = None,
    expected_project: Optional[Any] = None,
) -> Dict[str, Any]:
    """
    Validate and sanitize a raw source reference dictionary.
    Rejects invalid types, non-existent chunks, cross-project papers, and malformed inputs.
    """
    if not isinstance(source, dict):
        raise InvalidCitationError(f"Source reference must be a dictionary, got {type(source)}.")

    raw_pid = source.get("paper_id")
    if raw_pid is None and source.get("citation_id"):
        try:
            parsed = parse_citation_id(str(source["citation_id"]))
            raw_pid = parsed["paper_id"]
            if source.get("chunk_id") is None and parsed.get("chunk_id") is not None:
                source["chunk_id"] = parsed["chunk_id"]
        except Exception:
            pass

    if raw_pid is None:
        raise InvalidCitationError("Source reference missing 'paper_id'.")
    try:
        pid = int(raw_pid)
        if pid <= 0:
            raise ValueError()
    except (ValueError, TypeError):
        raise InvalidCitationError(f"Invalid 'paper_id': {raw_pid}. Must be a positive integer.")

    raw_cid = source.get("chunk_id")
    cid = None
    if raw_cid is not None:
        try:
            cid = int(raw_cid)
            if cid <= 0:
                raise ValueError()
        except (ValueError, TypeError):
            raise InvalidCitationError(f"Invalid 'chunk_id': {raw_cid}. Must be a positive integer.")

    paper_obj = None
    if allowed_papers is not None:
        paper_map = allowed_papers if isinstance(allowed_papers, dict) else {p.id: p for p in allowed_papers}
        if pid not in paper_map:
            raise InvalidCitationError(f"Paper ID {pid} is not among the allowed papers.")
        paper_obj = paper_map[pid]

    if expected_project is not None:
        expected_project_id = expected_project.id if hasattr(expected_project, "id") else int(expected_project)
        if paper_obj is not None:
            if paper_obj.project_id != expected_project_id:
                raise CrossProjectCitationError(
                    f"Cross-project source rejected: paper {pid} does not belong to project {expected_project_id}."
                )
        else:
            db_paper = Paper.objects.filter(id=pid).first()
            if not db_paper:
                raise InvalidCitationError(f"Paper ID {pid} does not exist.")
            if db_paper.project_id != expected_project_id:
                raise CrossProjectCitationError(
                    f"Cross-project source rejected: paper {pid} does not belong to project {expected_project_id}."
                )
            paper_obj = db_paper

    page_number = source.get("page_number")
    text = source.get("text", "")

    if valid_chunk_map is not None and cid is not None:
        if cid not in valid_chunk_map:
            raise InvalidCitationError(f"Chunk ID {cid} is not in the valid retrieved chunk set.")
        chunk_obj = valid_chunk_map[cid]
        if chunk_obj.paper_id != pid:
            raise InvalidCitationError(f"Chunk ID {cid} belongs to paper {chunk_obj.paper_id}, not {pid}.")
        page_number = chunk_obj.page_number
        text = chunk_obj.text
        if paper_obj is None:
            paper_obj = chunk_obj.paper

    paper_title = paper_obj.title if paper_obj else source.get("paper_title", "")
    citation_id = build_citation_id(pid, cid)

    return {
        "citation_id": citation_id,
        "citation_key": citation_id,
        "paper_id": pid,
        "paper_title": paper_title,
        "chunk_id": cid,
        "page_number": page_number,
        "text": text,
    }


def generate_citations_from_sources(
    sources: List[Dict[str, Any]],
    allowed_papers: Union[List[Paper], Dict[int, Paper]],
    valid_chunk_map: Optional[Dict[int, PaperChunk]] = None,
    expected_project: Optional[Any] = None,
) -> List[CitationReference]:
    """
    Generate deduplicated CitationReference objects from a list of source dictionaries.
    """
    if not isinstance(sources, list):
        raise InvalidCitationError("sources must be a list.")

    paper_map = allowed_papers if isinstance(allowed_papers, dict) else {p.id: p for p in allowed_papers}
    citations = []
    seen_keys: Set[Any] = set()

    for src in sources:
        validated = validate_source_dict(
            source=src,
            valid_chunk_map=valid_chunk_map,
            allowed_papers=paper_map,
            expected_project=expected_project,
        )

        dedup_key = (validated["paper_id"], validated["chunk_id"])
        if dedup_key in seen_keys:
            continue
        seen_keys.add(dedup_key)

        citations.append(CitationReference(
            citation_id=validated["citation_id"],
            citation_key=validated["citation_key"],
            paper_id=validated["paper_id"],
            paper_title=validated["paper_title"],
            chunk_id=validated["chunk_id"],
            page_number=validated["page_number"],
            text=validated["text"],
        ))

    return citations


def resolve_citation(
    citation_ref: Union[str, Dict[str, Any], CitationReference],
    evidence_items: Optional[Union[List[ResearchEvidence], QuerySet]] = None,
    message: Optional[ResearchMessage] = None,
    session: Optional[ResearchSession] = None,
    expected_project: Optional[Any] = None,
) -> ResearchEvidence:
    """
    Resolve a citation reference to its backing ResearchEvidence record.
    Matches by citation_id, evidence_id, or (paper_id, chunk_id).
    Validates session/message/project boundaries.
    """
    target_evidence_id = None
    target_paper_id = None
    target_chunk_id = None
    target_citation_id = None

    if isinstance(citation_ref, str):
        target_citation_id = citation_ref
        parsed = parse_citation_id(citation_ref)
        target_paper_id = parsed["paper_id"]
        target_chunk_id = parsed["chunk_id"]
    elif isinstance(citation_ref, CitationReference):
        target_citation_id = citation_ref.citation_id
        target_evidence_id = citation_ref.evidence_id
        target_paper_id = citation_ref.paper_id
        target_chunk_id = citation_ref.chunk_id
    elif isinstance(citation_ref, dict):
        target_citation_id = citation_ref.get("citation_id") or citation_ref.get("citation_key")
        target_evidence_id = citation_ref.get("evidence_id")
        target_paper_id = citation_ref.get("paper_id")
        target_chunk_id = citation_ref.get("chunk_id")
        if not target_paper_id and target_citation_id:
            parsed = parse_citation_id(target_citation_id)
            target_paper_id = parsed["paper_id"]
            target_chunk_id = parsed["chunk_id"]
    else:
        raise InvalidCitationError(f"Unsupported citation reference type: {type(citation_ref)}")

    if target_evidence_id is not None:
        try:
            target_evidence_id = int(target_evidence_id)
        except (ValueError, TypeError):
            raise InvalidCitationError(f"Invalid evidence_id: {target_evidence_id}")

    if message is not None:
        if not isinstance(message, ResearchMessage):
            raise InvalidCitationError("message must be a ResearchMessage instance.")
        candidates = list(message.evidence.select_related("paper", "chunk").all())
    elif session is not None:
        if not isinstance(session, ResearchSession):
            raise InvalidCitationError("session must be a ResearchSession instance.")
        candidates = list(ResearchEvidence.objects.filter(message__session=session).select_related("paper", "chunk"))
    elif evidence_items is not None:
        candidates = list(evidence_items)
    else:
        if target_evidence_id:
            candidates = list(ResearchEvidence.objects.filter(id=target_evidence_id).select_related("paper", "chunk"))
        elif target_paper_id and target_chunk_id:
            candidates = list(ResearchEvidence.objects.filter(paper_id=target_paper_id, chunk_id=target_chunk_id).select_related("paper", "chunk"))
        else:
            raise InvalidCitationError("Insufficient information to resolve citation (no context or ID).")

    expected_project_id = None
    if expected_project is not None:
        expected_project_id = expected_project.id if hasattr(expected_project, "id") else int(expected_project)

    for ev in candidates:
        if expected_project_id is not None and ev.paper.project_id != expected_project_id:
            raise CrossProjectCitationError(
                f"Cross-project evidence resolution rejected: evidence belongs to project {ev.paper.project_id}, expected {expected_project_id}."
            )

        if target_evidence_id is not None and ev.id == target_evidence_id:
            return ev

        if target_paper_id is not None and ev.paper_id == target_paper_id:
            if target_chunk_id is not None:
                if ev.chunk_id == target_chunk_id:
                    return ev
            else:
                return ev

    raise CitationResolutionError(
        f"Citation '{target_citation_id or target_evidence_id}' could not be resolved to valid evidence in the given context."
    )


def resolve_citations_for_message(
    message: ResearchMessage,
    expected_project: Optional[Any] = None,
) -> List[CitationReference]:
    """
    Resolve all evidence items for a ResearchMessage into CitationReference objects.
    """
    if not isinstance(message, ResearchMessage):
        raise InvalidCitationError("message must be a ResearchMessage instance.")
    evidence_qs = message.evidence.select_related("paper", "chunk").order_by("created_at")
    return generate_citations_from_evidence(evidence_qs, expected_project=expected_project)


# ==============================================================================
# Phase 7.5.2 — Citation Formatting & Numbering Helpers
# ==============================================================================

def format_citation_label(number: Union[int, str]) -> str:
    """
    Format a positive integer citation number into standard academic bracket format: [1], [2], etc.
    Accepts positive int or numeric str (e.g. 1, '1', or '[1]').
    """
    if isinstance(number, bool):
        raise InvalidCitationError(f"Citation number must be a positive integer, got boolean {number}.")
    if isinstance(number, str):
        cleaned = number.strip().lstrip("[").rstrip("]").strip()
        try:
            val = int(cleaned)
        except ValueError:
            raise InvalidCitationError(f"Invalid citation number string: '{number}'")
    elif isinstance(number, int):
        val = number
    else:
        raise InvalidCitationError(f"Citation number must be a positive integer, got {type(number)}.")

    if val <= 0:
        raise InvalidCitationError(f"Citation number must be a positive integer, got {val}.")

    return f"[{val}]"


def parse_citation_label(label: Union[str, int]) -> int:
    """
    Parse a bracketed citation label '[1]' or numeric string '1' into its positive integer value.
    """
    if not isinstance(label, (str, int)) or isinstance(label, bool):
        raise InvalidCitationError(f"Citation label must be a string or int, got {type(label)}.")
    cleaned = str(label).strip()
    if cleaned.startswith("[") and cleaned.endswith("]"):
        cleaned = cleaned[1:-1].strip()
    try:
        val = int(cleaned)
        if val <= 0:
            raise ValueError()
        return val
    except ValueError:
        raise InvalidCitationError(f"Cannot parse valid positive integer from citation label '{label}'.")


def extract_sources_from_payload(payload: Any) -> List[Dict[str, Any]]:
    """
    Recursively/iteratively extract source references from AI endpoint responses or data dicts.
    Supports single-paper answers, multi-paper comparison, gap analysis, thematic analysis,
    and research trends.
    """
    sources: List[Dict[str, Any]] = []
    if payload is None:
        return sources

    if isinstance(payload, list):
        for item in payload:
            sources.extend(extract_sources_from_payload(item))
        return sources

    if isinstance(payload, dict):
        # 1. If payload contains top-level sources list
        if "sources" in payload and isinstance(payload["sources"], list):
            for s in payload["sources"]:
                if isinstance(s, dict):
                    sources.append(s)

        # 2. If payload contains top-level source_refs list
        if "source_refs" in payload and isinstance(payload["source_refs"], list):
            for s in payload["source_refs"]:
                if isinstance(s, dict):
                    sources.append(s)

        # 3. Known multi-paper sections
        section_keys = [
            "comparison", "gap_analysis", "thematic_analysis", "trend_analysis",
            "similarities", "differences", "methodology_comparison", "findings_comparison",
            "research_gaps", "common_limitations", "methodological_gaps", "dataset_population_gaps",
            "understudied_areas", "contradictions_inconsistencies", "unanswered_research_questions",
            "future_research_directions", "themes", "research_evolution", "emerging_directions",
            "methodology_evolution", "future_directions", "papers"
        ]
        for key in section_keys:
            if key in payload and payload[key] is not None:
                sources.extend(extract_sources_from_payload(payload[key]))

        # 4. If payload itself is a single source dict (has paper_id or citation_id, but not a container)
        if ("paper_id" in payload or "citation_id" in payload or "chunk_id" in payload):
            if "overall_synthesis" not in payload and "comparison" not in payload and "themes" not in payload and "trend_analysis" not in payload and "gap_analysis" not in payload:
                sources.append(payload)

    return sources


def build_citation_map(
    items: Union[List[Any], QuerySet, ResearchMessage, Dict[str, Any]],
    start_number: int = 1,
    expected_project: Optional[Any] = None,
    allowed_papers: Optional[Union[List[Paper], Dict[int, Paper]]] = None,
    valid_chunk_map: Optional[Dict[int, PaperChunk]] = None,
) -> Dict[str, Dict[str, Any]]:
    """
    Build a deterministic, structured citation map for frontend and API responses.
    Number citations deterministically based on their first appearance:
        cite_p1_c4 -> [1]
        cite_p2_c7 -> [2]
        cite_p1_c9 -> [3]
    Duplicate citation IDs receive only one citation number.
    Missing page numbers are preserved as None without inventing page numbers.
    Structure:
    {
      "1": {
        "citation_id": "cite_p1_c4",
        "paper_id": 1,
        "paper_title": "...",
        "chunk_id": 4,
        "page_number": 3,
        "evidence_id": 17
      }
    }
    """
    if not isinstance(start_number, int) or isinstance(start_number, bool) or start_number < 1:
        raise InvalidCitationError("start_number must be a positive integer >= 1.")

    expected_project_id = None
    if expected_project is not None:
        expected_project_id = expected_project.id if hasattr(expected_project, "id") else int(expected_project)

    paper_map = None
    if allowed_papers is not None:
        paper_map = allowed_papers if isinstance(allowed_papers, dict) else {p.id: p for p in allowed_papers}

    # Resolve items container
    raw_list: List[Any] = []
    if isinstance(items, ResearchMessage):
        raw_list = list(items.evidence.select_related("paper", "chunk").order_by("created_at"))
    elif hasattr(items, "select_related"):  # QuerySet
        raw_list = list(items)
    elif isinstance(items, dict):
        raw_list = extract_sources_from_payload(items)
    elif isinstance(items, list):
        raw_list = items
    elif items is None:
        raw_list = []
    else:
        raise InvalidCitationError(f"Unsupported items type for build_citation_map: {type(items)}")

    citation_map: Dict[str, Dict[str, Any]] = {}
    seen_citation_ids: Dict[str, int] = {}
    current_number = start_number

    for item in raw_list:
        if item is None:
            continue

        cid: Optional[str] = None
        pid: Optional[int] = None
        cid_chunk: Optional[int] = None
        ptitle: str = ""
        pnum: Optional[int] = None
        ev_id: Optional[int] = None

        if isinstance(item, ResearchEvidence):
            if expected_project_id is not None and item.paper.project_id != expected_project_id:
                raise CrossProjectCitationError(
                    f"Cross-project evidence rejected: evidence {item.id} belongs to project "
                    f"{item.paper.project_id}, expected {expected_project_id}."
                )
            if paper_map is not None and item.paper_id not in paper_map:
                raise InvalidCitationError(f"Paper ID {item.paper_id} is not in allowed papers.")

            cid = item.citation_id
            pid = item.paper_id
            cid_chunk = item.chunk_id
            ptitle = item.paper.title
            pnum = item.page_number
            ev_id = item.id

        elif isinstance(item, CitationReference):
            if expected_project_id is not None:
                db_paper = Paper.objects.filter(id=item.paper_id).first()
                if db_paper and db_paper.project_id != expected_project_id:
                    raise CrossProjectCitationError(
                        f"Cross-project reference rejected: paper {item.paper_id} belongs to "
                        f"project {db_paper.project_id}, expected {expected_project_id}."
                    )
            if paper_map is not None and item.paper_id not in paper_map:
                raise InvalidCitationError(f"Paper ID {item.paper_id} is not in allowed papers.")

            cid = item.citation_id
            pid = item.paper_id
            cid_chunk = item.chunk_id
            ptitle = item.paper_title
            pnum = item.page_number
            ev_id = item.evidence_id

        elif isinstance(item, NumberedCitation):
            cid = item.citation_id
            pid = item.paper_id
            cid_chunk = item.chunk_id
            ptitle = item.paper_title
            pnum = item.page_number
            ev_id = item.evidence_id

        elif isinstance(item, dict):
            validated = validate_source_dict(
                source=item,
                valid_chunk_map=valid_chunk_map,
                allowed_papers=paper_map,
                expected_project=expected_project_id,
            )
            cid = validated["citation_id"]
            pid = validated["paper_id"]
            cid_chunk = validated["chunk_id"]
            ptitle = validated["paper_title"]
            pnum = validated["page_number"]
            raw_ev_id = item.get("evidence_id")
            if raw_ev_id is not None:
                try:
                    ev_id = int(raw_ev_id)
                except (ValueError, TypeError):
                    raise InvalidCitationError(f"Invalid evidence_id in source dict: {raw_ev_id}")

        elif isinstance(item, str):
            parsed = parse_citation_id(item)
            pid = parsed["paper_id"]
            cid_chunk = parsed["chunk_id"]
            cid = item
            if expected_project_id is not None or paper_map is not None:
                db_paper = Paper.objects.filter(id=pid).first()
                if not db_paper:
                    raise InvalidCitationError(f"Paper ID {pid} does not exist.")
                if expected_project_id is not None and db_paper.project_id != expected_project_id:
                    raise CrossProjectCitationError(
                        f"Cross-project citation rejected: paper {pid} belongs to project {db_paper.project_id}."
                    )
                if paper_map is not None and pid not in paper_map:
                    raise InvalidCitationError(f"Paper ID {pid} is not in allowed papers.")
                ptitle = db_paper.title
            else:
                db_paper = Paper.objects.filter(id=pid).first()
                ptitle = db_paper.title if db_paper else ""

        else:
            raise InvalidCitationError(f"Unsupported citation item type: {type(item)}")

        # Deduplication check by citation_id
        if cid in seen_citation_ids:
            existing_num = seen_citation_ids[cid]
            existing_key = str(existing_num)
            if ev_id is not None and citation_map[existing_key].get("evidence_id") is None:
                citation_map[existing_key]["evidence_id"] = ev_id
            continue

        assigned_num = current_number
        seen_citation_ids[cid] = assigned_num
        citation_map[str(assigned_num)] = {
            "citation_id": cid,
            "paper_id": pid,
            "paper_title": ptitle,
            "chunk_id": cid_chunk,
            "page_number": pnum,
            "evidence_id": ev_id,
        }
        current_number += 1

    return citation_map


def resolve_citation_by_number(
    citation_map: Dict[str, Dict[str, Any]],
    number: Union[int, str],
) -> Dict[str, Any]:
    """
    Resolve a citation number ([1], '1', 1) back to its citation metadata entry from citation_map.
    Raises CitationResolutionError if the citation number is not found.
    """
    if not isinstance(citation_map, dict):
        raise InvalidCitationError(f"citation_map must be a dictionary, got {type(citation_map)}.")

    num_int = parse_citation_label(number)
    key = str(num_int)
    if key not in citation_map:
        raise CitationResolutionError(f"Citation [{key}] could not be resolved in the provided citation map.")

    return citation_map[key]


def get_citation_number_for_id(
    citation_map: Dict[str, Dict[str, Any]],
    citation_id: str,
) -> Optional[int]:
    """
    Find the assigned sequential citation number for a given citation_id in citation_map.
    Returns integer number (e.g. 1) or None if not present.
    """
    if not isinstance(citation_map, dict) or not isinstance(citation_id, str):
        return None

    for key, val in citation_map.items():
        if isinstance(val, dict) and val.get("citation_id") == citation_id:
            try:
                return int(key)
            except ValueError:
                pass
    return None


def get_citation_label_for_id(
    citation_map: Dict[str, Dict[str, Any]],
    citation_id: str,
) -> Optional[str]:
    """
    Find the bracketed citation label '[N]' for a given citation_id in citation_map.
    """
    num = get_citation_number_for_id(citation_map, citation_id)
    if num is not None:
        return format_citation_label(num)
    return None


def format_citations_summary(
    citation_map: Dict[str, Dict[str, Any]],
) -> List[Dict[str, Any]]:
    """
    Return a list of numbered citations ordered sequentially:
    [
        {"number": 1, "label": "[1]", **citation_entry},
        {"number": 2, "label": "[2]", **citation_entry},
    ]
    """
    if not isinstance(citation_map, dict):
        raise InvalidCitationError(f"citation_map must be a dictionary, got {type(citation_map)}.")

    summary = []
    sorted_keys = sorted([k for k in citation_map.keys() if k.isdigit()], key=int)
    for k in sorted_keys:
        entry = citation_map[k]
        num = int(k)
        summary.append({
            "number": num,
            "label": format_citation_label(num),
            **entry,
        })
    return summary

