# Generated by Django 4.2.30 on 2026-09-07 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='extracted_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
